import javax.swing.*;
/**
 * Created by Naxster on 2015-01-10.
 */
public class MainWindow extends JFrame{
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JComboBox jComboBox1;
    // End of variables declaration//GEN-END:variables
    private AdditionalWindow okno1;
    private AdditionalWindow okno2;
    private AdditionalWindow okno3;
    private AdditionalWindow okno4;
    private AdditionalWindow okno5;

    public MainWindow() {
        initComponents();
        java.awt.Dimension ekran = java.awt.Toolkit.getDefaultToolkit().getScreenSize();// pobierz rozmiar ekranu
        this.setSize(ekran.width - (ekran.width / 2), ekran.height - (ekran.height / 2)); // ustawiamy rozmiar okna.
        this.setLocationRelativeTo(null); // null oznacza że chcemy umieścić okno na środku ekranu.
        setVisible(true);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Okno główne");

        jComboBox1.setMaximumRowCount(5);
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "okno1", "okno2", "okno3", "okno4", "okno5" }));

        jButton1.setText("jButton1");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(85, 85, 85)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 172, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(61, 61, 61)
                                .addComponent(jButton1)
                                .addContainerGap(105, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jButton1)
                                        .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addContainerGap(127, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        switch (jComboBox1.getSelectedIndex()) {
            case 0: {
                if(okno1 != null)
                    okno1.dispose();
                okno1 = new AdditionalWindow("okno1");
                break;
            }
            case 1: {
                if(okno2 != null)
                    okno2.dispose();
                okno2 = new AdditionalWindow("okno2");
                break;
            }
            case 2: {
                if(okno3 != null)
                    okno3.dispose();
                okno3 = new AdditionalWindow("okno3");
                break;
            }
            case 3: {
                if(okno4 != null)
                    okno4.dispose();
                okno4 = new AdditionalWindow("okno4");
                break;
            }
            case 4: {
                if(okno5 != null)
                    okno5.dispose();
                okno5 = new AdditionalWindow("okno5");
                break;
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed


}